#include "GeoData.h"
#include <QDebug>


const QHash<QString, QString> GeoData::codeNameHash = {
    {"AF", "Afghanistan"},
    {"AX", "Åland Islands"},
    {"AL", "Albania"},
    {"DZ", "Algeria"},
    {"AS", "American Samoa"},
    {"AD", "Andorra"},
    {"AO", "Angola"},
    {"AI", "Anguilla"},
    {"AQ", "Antarctica"},
    {"AG", "Antigua and Barbuda"},
    {"AR", "Argentina"},
    {"AM", "Armenia"},
    {"AW", "Aruba"},
    {"AU", "Australia"},
    {"AT", "Austria"},
    {"AZ", "Azerbaijan"},
    {"BS", "Bahamas"},
    {"BH", "Bahrain"},
    {"BD", "Bangladesh"},
    {"BB", "Barbados"},
    {"BY", "Belarus"},
    {"BE", "Belgium"},
    {"BZ", "Belize"},
    {"BJ", "Benin"},
    {"BM", "Bermuda"},
    {"BT", "Bhutan"},
    {"BO", "Bolivia"},
    {"BQ", "Bonaire"},
    {"BA", "Bosnia and Herzegovina"},
    {"BW", "Botswana"},
    {"BV", "Bouvet Island"},
    {"BR", "Brazil"},
    {"IO", "British Indian Ocean Territory"},
    {"BN", "Brunei Darussalam"},
    {"BG", "Bulgaria"},
    {"BF", "Burkina Faso"},
    {"BI", "Burundi"},
    {"CV", "Cabo Verde"},
    {"KH", "Cambodia"},
    {"CM", "Cameroon"},
    {"CA", "Canada"},
    {"KY", "Cayman Islands"},
    {"CF", "Central African Republic"},
    {"TD", "Chad"},
    {"CL", "Chile"},
    {"CN", "China"},
    {"CX", "Christmas Island"},
    {"CC", "Cocos  Islands"},
    {"CO", "Colombia"},
    {"KM", "Comoros"},
    {"CD", "Congo"},
    {"CG", "Congo"},
    {"CK", "Cook Islands"},
    {"CR", "Costa Rica"},
    {"CI", "Côte d'Ivoire"},
    {"HR", "Croatia"},
    {"CU", "Cuba"},
    {"CW", "Curaçao"},
    {"CY", "Cyprus"},
    {"CZ", "Czechia"},
    {"DK", "Denmark"},
    {"DJ", "Djibouti"},
    {"DM", "Dominica"},
    {"DO", "Dominican Republic"},
    {"EC", "Ecuador"},
    {"EG", "Egypt"},
    {"SV", "El Salvador"},
    {"GQ", "Equatorial Guinea"},
    {"ER", "Eritrea"},
    {"EE", "Estonia"},
    {"SZ", "Eswatini"},
    {"ET", "Ethiopia"},
    {"FK", "Falkland Islands"},
    {"FO", "Faroe Islands"},
    {"FJ", "Fiji"},
    {"FI", "Finland"},
    {"FR", "France"},
    {"GF", "French Guiana"},
    {"PF", "French Polynesia"},
    {"TF", "French Southern Territories"},
    {"GA", "Gabon"},
    {"GM", "Gambia"},
    {"GE", "Georgia"},
    {"DE", "Germany"},
    {"GH", "Ghana"},
    {"GI", "Gibraltar"},
    {"GR", "Greece"},
    {"GL", "Greenland"},
    {"GD", "Grenada"},
    {"GP", "Guadeloupe"},
    {"GU", "Guam"},
    {"GT", "Guatemala"},
    {"GG", "Guernsey"},
    {"GN", "Guinea"},
    {"GW", "Guinea-Bissau"},
    {"GY", "Guyana"},
    {"HT", "Haiti"},
    {"HM", "Heard Island and McDonald Islands"},
    {"VA", "Vatican City"},
    {"HN", "Honduras"},
    {"HK", "Hong Kong"},
    {"HU", "Hungary"},
    {"IS", "Iceland"},
    {"IN", "India"},
    {"ID", "Indonesia"},
    {"IR", "Iran"},
    {"IQ", "Iraq"},
    {"IE", "Ireland"},
    {"IM", "Isle of Man"},
    {"IL", "Israel"},
    {"IT", "Italy"},
    {"JM", "Jamaica"},
    {"JP", "Japan"},
    {"JE", "Jersey"},
    {"JO", "Jordan"},
    {"KZ", "Kazakhstan"},
    {"KE", "Kenya"},
    {"KI", "Kiribati"},
    {"KP", "North Korea"},
    {"KR", "South Korea"},
    {"KW", "Kuwait"},
    {"KG", "Kyrgyzstan"},
    {"LA", "Lao People's Democratic Republic"},
    {"LV", "Latvia"},
    {"LB", "Lebanon"},
    {"LS", "Lesotho"},
    {"LR", "Liberia"},
    {"LY", "Libya"},
    {"LI", "Liechtenstein"},
    {"LT", "Lithuania"},
    {"LU", "Luxembourg"},
    {"MO", "Macao"},
    {"MK", "North Macedonia"},
    {"MG", "Madagascar"},
    {"MW", "Malawi"},
    {"MY", "Malaysia"},
    {"MV", "Maldives"},
    {"ML", "Mali"},
    {"MT", "Malta"},
    {"MH", "Marshall Islands"},
    {"MQ", "Martinique"},
    {"MR", "Mauritania"},
    {"MU", "Mauritius"},
    {"YT", "Mayotte"},
    {"MX", "Mexico"},
    {"FM", "Micronesia"},
    {"MD", "Moldova"},
    {"MC", "Monaco"},
    {"MN", "Mongolia"},
    {"ME", "Montenegro"},
    {"MS", "Montserrat"},
    {"MA", "Morocco"},
    {"MZ", "Mozambique"},
    {"MM", "Myanmar"},
    {"NA", "Namibia"},
    {"NR", "Nauru"},
    {"NP", "Nepal"},
    {"NL", "Netherlands"},
    {"NC", "New Caledonia"},
    {"NZ", "New Zealand"},
    {"NI", "Nicaragua"},
    {"NE", "Niger"},
    {"NG", "Nigeria"},
    {"NU", "Niue"},
    {"NF", "Norfolk Island"},
    {"MP", "Northern Mariana Islands"},
    {"NO", "Norway"},
    {"OM", "Oman"},
    {"PK", "Pakistan"},
    {"PW", "Palau"},
    {"PS", "Palestine"},
    {"PA", "Panama"},
    {"PG", "Papua New Guinea"},
    {"PY", "Paraguay"},
    {"PE", "Peru"},
    {"PH", "Philippines"},
    {"PN", "Pitcairn"},
    {"PL", "Poland"},
    {"PT", "Portugal"},
    {"PR", "Puerto Rico"},
    {"QA", "Qatar"},
    {"RE", "Réunion"},
    {"RO", "Romania"},
    {"RU", "Russian Federation"},
    {"RW", "Rwanda"},
    {"BL", "Saint Barthélemy"},
    {"SH", "Saint Helena"},
    {"KN", "Saint Kitts and Nevis"},
    {"LC", "Saint Lucia"},
    {"MF", "Saint Martin"},
    {"PM", "Saint Pierre and Miquelon"},
    {"VC", "Saint Vincent and the Grenadines"},
    {"WS", "Samoa"},
    {"SM", "San Marino"},
    {"ST", "Sao Tome and Principe"},
    {"SA", "Saudi Arabia"},
    {"SN", "Senegal"},
    {"RS", "Serbia"},
    {"SC", "Seychelles"},
    {"SL", "Sierra Leone"},
    {"SG", "Singapore"},
    {"SX", "Sint Maarten"},
    {"SK", "Slovakia"},
    {"SI", "Slovenia"},
    {"SB", "Solomon Islands"},
    {"SO", "Somalia"},
    {"ZA", "South Africa"},
    {"GS", "South Georgia and the South Sandwich Islands"},
    {"SS", "South Sudan"},
    {"ES", "Spain"},
    {"LK", "Sri Lanka"},
    {"SD", "Sudan"},
    {"SR", "Suriname"},
    {"SJ", "Svalbard and Jan Mayen"},
    {"SE", "Sweden"},
    {"CH", "Switzerland"},
    {"SY", "Syria"},
    {"TW", "Taiwan"},
    {"TJ", "Tajikistan"},
    {"TZ", "Tanzania"},
    {"TH", "Thailand"},
    {"TL", "Timor-Leste"},
    {"TG", "Togo"},
    {"TK", "Tokelau"},
    {"TO", "Tonga"},
    {"TT", "Trinidad and Tobago"},
    {"TN", "Tunisia"},
    {"TR", "Turkey"},
    {"TM", "Turkmenistan"},
    {"TC", "Turks and Caicos Islands"},
    {"TV", "Tuvalu"},
    {"UG", "Uganda"},
    {"UA", "Ukraine"},
    {"AE", "United Arab Emirates"},
    {"GB", "United Kingdom"},
    {"UM", "United States Minor Outlying Islands"},
    {"US", "United States"},
    {"UY", "Uruguay"},
    {"UZ", "Uzbekistan"},
    {"VU", "Vanuatu"},
    {"VE", "Venezuela"},
    {"VN", "Viet Nam"},
    {"VG", "Virgin Islands"},
    {"VI", "Virgin Islands"},
    {"WF", "Wallis and Futuna"},
    {"EH", "Western Sahara"},
    {"YE", "Yemen"},
    {"ZM", "Zambia"},
    {"ZW", "Zimbabwe"}
};

const QHash<QString, QString> GeoData::countryRegionHash = {
    {"AR", "South America"},
    {"BO", "South America"},
    {"BR", "South America"},
    {"CL", "South America"},
    {"CO", "South America"},
    {"EC", "South America"},
    {"GF", "South America"},
    {"GY", "South America"},
    {"PY", "South America"},
    {"PE", "South America"},
    {"SR", "South America"},
    {"UY", "South America"},
    {"VE", "South America"},
    {"IN", "India and the Middle East"},
    {"BH", "India and the Middle East"},
    {"CY", "India and the Middle East"},
    {"EG", "India and the Middle East"},
    {"IR", "India and the Middle East"},
    {"IQ", "India and the Middle East"},
    {"IL", "India and the Middle East"},
    {"JO", "India and the Middle East"},
    {"KW", "India and the Middle East"},
    {"LB", "India and the Middle East"},
    {"OM", "India and the Middle East"},
    {"PS", "India and the Middle East"},
    {"QA", "India and the Middle East"},
    {"SA", "India and the Middle East"},
    {"SY", "India and the Middle East"},
    {"TR", "India and the Middle East"},
    {"AE", "India and the Middle East"},
    {"AL", "Europe"},
    {"AD", "Europe"},
    {"AT", "Europe"},
    {"BY", "Europe"},
    {"BE", "Europe"},
    {"BA", "Europe"},
    {"BG", "Europe"},
    {"HR", "Europe"},
    {"CZ", "Europe"},
    {"DK", "Europe"},
    {"EE", "Europe"},
    {"FI", "Europe"},
    {"FR", "Europe"},
    {"DE", "Europe"},
    {"GR", "Europe"},
    {"HU", "Europe"},
    {"IS", "Europe"},
    {"IE", "Europe"},
    {"IT", "Europe"},
    {"LV", "Europe"},
    {"LI", "Europe"},
    {"LT", "Europe"},
    {"LU", "Europe"},
    {"MT", "Europe"},
    {"MD", "Europe"},
    {"MC", "Europe"},
    {"ME", "Europe"},
    {"NL", "Europe"},
    {"MK", "Europe"},
    {"NO", "Europe"},
    {"PL", "Europe"},
    {"PT", "Europe"},
    {"RO", "Europe"},
    {"SM", "Europe"},
    {"RS", "Europe"},
    {"SK", "Europe"},
    {"SI", "Europe"},
    {"ES", "Europe"},
    {"SE", "Europe"},
    {"CH", "Europe"},
    {"UA", "Europe"},
    {"GB", "Europe"},
    {"VA", "Europe"},
    {"BD", "Asia (South)"},
    {"BT", "Asia (South)"},
    {"MV", "Asia (South)"},
    {"NP", "Asia (South)"},
    {"PK", "Asia (South)"},
    {"LK", "Asia (South)"},
    {"AF", "Asia (South)"},
    {"CN", "Asia (East)"},
    {"MN", "Asia (East)"},
    {"TW", "Asia (East)"},
    {"HK", "Asia (East)"},
    {"MO", "Asia (East)"}
};

const QHash<QString, QString> GeoData::stateRegionHash = {
    {"Mississippi", "East"},
    {"Massachusetts", "East"},
    {"North Carolina", "East"},
    {"Tennessee", "East"},
    {"Florida", "East"},
    {"Maryland", "East"},
    {"New York", "East"},
    {"Georgia", "East"},
    {"Maine", "East"},
    {"West Virginia", "East"},
    {"Alabama", "East"},
    {"Virginia", "East"},
    {"Vermont", "East"},
    {"Delaware", "East"},
    {"Rhode Island", "East"},
    {"Kentucky", "East"},
    {"New Hampshire", "East"},
    {"Pennsylvania", "East"},
    {"Connecticut", "East"},
    {"New Jersey", "East"},
    {"South Carolina", "East"},
    {"Arkansas", "Central"},
    {"Wisconsin", "Central"},
    {"Texas", "Central"},
    {"Illinois", "Central"},
    {"North Dakota", "Central"},
    {"Oklahoma", "Central"},
    {"Minnesota", "Central"},
    {"Iowa", "Central"},
    {"Michigan", "Central"},
    {"Louisiana", "Central"},
    {"Missouri", "Central"},
    {"Indiana", "Central"},
    {"South Dakota", "Central"},
    {"Ohio", "Central"},
    {"Nebraska", "Central"},
    {"Kansas", "Central"},
    {"Alaska", "West"},
    {"Idaho", "West"},
    {"Montana", "West"},
    {"Wyoming", "West"},
    {"Washington", "West"},
    {"Colorado", "West"},
    {"New Mexico", "West"},
    {"Hawaii", "West"},
    {"Oregon", "West"},
    {"California", "West"},
    {"Arizona", "West"},
    {"Utah", "West"},
    {"Nevada", "West"}
};

QString GeoData::countryCodeToName(const QString &code)
{
    if (!codeNameHash.contains(code)) {
        qWarning() << "Country code not found: " << code;
        return QString("");
    }

    return codeNameHash.value(code);
}

QString GeoData::stateToRegionUS(const QString &state)
{
    if (!stateRegionHash.contains(state)) {
        qWarning() << "State not found: " << state;
        return QString("");
    }

    return stateRegionHash.value(state);
}

QString GeoData::countryCodeToRegion(const QString &code)
{
    if (!countryRegionHash.contains(code))
        return QString("");

    return countryRegionHash.value(code);
}
